package com.Ape.dataObject;

public class DO_Merchant {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column merchant.id
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column merchant.merchant_name
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	private String merchantName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column merchant.merchant_type
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	private String merchantType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column merchant.description
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column merchant.address
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column merchant.img_url
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	private String imgUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column merchant.id
	 * @return  the value of merchant.id
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column merchant.id
	 * @param id  the value for merchant.id
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column merchant.merchant_name
	 * @return  the value of merchant.merchant_name
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public String getMerchantName() {
		return merchantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column merchant.merchant_name
	 * @param merchantName  the value for merchant.merchant_name
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName == null ? null : merchantName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column merchant.merchant_type
	 * @return  the value of merchant.merchant_type
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public String getMerchantType() {
		return merchantType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column merchant.merchant_type
	 * @param merchantType  the value for merchant.merchant_type
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public void setMerchantType(String merchantType) {
		this.merchantType = merchantType == null ? null : merchantType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column merchant.description
	 * @return  the value of merchant.description
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column merchant.description
	 * @param description  the value for merchant.description
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column merchant.address
	 * @return  the value of merchant.address
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column merchant.address
	 * @param address  the value for merchant.address
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column merchant.img_url
	 * @return  the value of merchant.img_url
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column merchant.img_url
	 * @param imgUrl  the value for merchant.img_url
	 * @mbg.generated  Sat Mar 07 12:31:37 CST 2020
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl == null ? null : imgUrl.trim();
	}
}