package com.Ape.dao;

import com.Ape.dataObject.DO_Friends;

public interface DO_FriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    int deleteByPrimaryKey(Integer usersid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    int insert(DO_Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    int insertSelective(DO_Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    DO_Friends selectByPrimaryKey(Integer usersid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    int updateByPrimaryKeySelective(DO_Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    int updateByPrimaryKey(DO_Friends record);
}