package com.Ape.dao;

import java.util.List;

import com.Ape.dataObject.DO_Merchants;

public interface DO_MerchantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    int insert(DO_Merchants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    int insertSelective(DO_Merchants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    DO_Merchants selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    int updateByPrimaryKeySelective(DO_Merchants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    int updateByPrimaryKey(DO_Merchants record);
    
    /**
     * @author Miao Xu
     */
    
    DO_Merchants selectByUsersId(Integer usersId);
    
    /**
     * @author Miao Xu
     */
    List<DO_Merchants> selectByType(String type);

}