package com.Ape.dao;

import java.util.List;

import com.Ape.dataObject.DO_Posts;

public interface DO_PostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    int insert(DO_Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    int insertSelective(DO_Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    DO_Posts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    int updateByPrimaryKeySelective(DO_Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    int updateByPrimaryKey(DO_Posts record);
    
    /**
     * @author Miao Xu
     * @param merchantsType
     */
    List<DO_Posts> selectByMerchantsType(String merchantsType);
}