package com.Ape.dao;

import com.Ape.dataObject.DO_UsersPassword;

public interface DO_UsersPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    int insert(DO_UsersPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    int insertSelective(DO_UsersPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    DO_UsersPassword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    int updateByPrimaryKeySelective(DO_UsersPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    int updateByPrimaryKey(DO_UsersPassword record);
    
    /**
     * @author Miao Xu
     */
    DO_UsersPassword selectByUsersId(Integer usersId);
}