package com.Ape.dao;

import com.Ape.dataObject.DO_Users;

public interface DO_UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    int insert(DO_Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    int insertSelective(DO_Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    DO_Users selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    int updateByPrimaryKeySelective(DO_Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    int updateByPrimaryKey(DO_Users record);
    
    /**
     * @author Miao Xu
     * @param username
     * @return DO_Users by username
     */
    DO_Users selectByUsername(String username);
}