package com.Ape.dataObject;

public class DO_CommentsStars {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentsstars.id
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentsstars.usersId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    private Integer usersid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentsstars.merchantsId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    private Integer merchantsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentsstars.postsId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    private Integer postsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentsstars.stars
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    private Integer stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentsstars.content
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentsstars.username
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentsstars.id
     *
     * @return the value of commentsstars.id
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentsstars.id
     *
     * @param id the value for commentsstars.id
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentsstars.usersId
     *
     * @return the value of commentsstars.usersId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public Integer getUsersid() {
        return usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentsstars.usersId
     *
     * @param usersid the value for commentsstars.usersId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public void setUsersid(Integer usersid) {
        this.usersid = usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentsstars.merchantsId
     *
     * @return the value of commentsstars.merchantsId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public Integer getMerchantsid() {
        return merchantsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentsstars.merchantsId
     *
     * @param merchantsid the value for commentsstars.merchantsId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public void setMerchantsid(Integer merchantsid) {
        this.merchantsid = merchantsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentsstars.postsId
     *
     * @return the value of commentsstars.postsId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public Integer getPostsid() {
        return postsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentsstars.postsId
     *
     * @param postsid the value for commentsstars.postsId
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public void setPostsid(Integer postsid) {
        this.postsid = postsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentsstars.stars
     *
     * @return the value of commentsstars.stars
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public Integer getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentsstars.stars
     *
     * @param stars the value for commentsstars.stars
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public void setStars(Integer stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentsstars.content
     *
     * @return the value of commentsstars.content
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentsstars.content
     *
     * @param content the value for commentsstars.content
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentsstars.username
     *
     * @return the value of commentsstars.username
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentsstars.username
     *
     * @param username the value for commentsstars.username
     *
     * @mbg.generated Mon Mar 16 00:18:54 CDT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}