package com.Ape.dataObject;

public class DO_Friends {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.usersId
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private Integer usersid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends1
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends2
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends3
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends4
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends5
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends6
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends7
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends8
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends9
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends10
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends11
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends12
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends13
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends14
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends15
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends16
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends17
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends18
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends19
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friends20
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    private String friends20;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.usersId
     *
     * @return the value of friends.usersId
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public Integer getUsersid() {
        return usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.usersId
     *
     * @param usersid the value for friends.usersId
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setUsersid(Integer usersid) {
        this.usersid = usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends1
     *
     * @return the value of friends.friends1
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends1() {
        return friends1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends1
     *
     * @param friends1 the value for friends.friends1
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends1(String friends1) {
        this.friends1 = friends1 == null ? null : friends1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends2
     *
     * @return the value of friends.friends2
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends2() {
        return friends2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends2
     *
     * @param friends2 the value for friends.friends2
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends2(String friends2) {
        this.friends2 = friends2 == null ? null : friends2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends3
     *
     * @return the value of friends.friends3
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends3() {
        return friends3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends3
     *
     * @param friends3 the value for friends.friends3
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends3(String friends3) {
        this.friends3 = friends3 == null ? null : friends3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends4
     *
     * @return the value of friends.friends4
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends4() {
        return friends4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends4
     *
     * @param friends4 the value for friends.friends4
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends4(String friends4) {
        this.friends4 = friends4 == null ? null : friends4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends5
     *
     * @return the value of friends.friends5
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends5() {
        return friends5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends5
     *
     * @param friends5 the value for friends.friends5
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends5(String friends5) {
        this.friends5 = friends5 == null ? null : friends5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends6
     *
     * @return the value of friends.friends6
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends6() {
        return friends6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends6
     *
     * @param friends6 the value for friends.friends6
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends6(String friends6) {
        this.friends6 = friends6 == null ? null : friends6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends7
     *
     * @return the value of friends.friends7
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends7() {
        return friends7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends7
     *
     * @param friends7 the value for friends.friends7
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends7(String friends7) {
        this.friends7 = friends7 == null ? null : friends7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends8
     *
     * @return the value of friends.friends8
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends8() {
        return friends8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends8
     *
     * @param friends8 the value for friends.friends8
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends8(String friends8) {
        this.friends8 = friends8 == null ? null : friends8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends9
     *
     * @return the value of friends.friends9
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends9() {
        return friends9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends9
     *
     * @param friends9 the value for friends.friends9
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends9(String friends9) {
        this.friends9 = friends9 == null ? null : friends9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends10
     *
     * @return the value of friends.friends10
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends10() {
        return friends10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends10
     *
     * @param friends10 the value for friends.friends10
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends10(String friends10) {
        this.friends10 = friends10 == null ? null : friends10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends11
     *
     * @return the value of friends.friends11
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends11() {
        return friends11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends11
     *
     * @param friends11 the value for friends.friends11
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends11(String friends11) {
        this.friends11 = friends11 == null ? null : friends11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends12
     *
     * @return the value of friends.friends12
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends12() {
        return friends12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends12
     *
     * @param friends12 the value for friends.friends12
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends12(String friends12) {
        this.friends12 = friends12 == null ? null : friends12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends13
     *
     * @return the value of friends.friends13
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends13() {
        return friends13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends13
     *
     * @param friends13 the value for friends.friends13
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends13(String friends13) {
        this.friends13 = friends13 == null ? null : friends13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends14
     *
     * @return the value of friends.friends14
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends14() {
        return friends14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends14
     *
     * @param friends14 the value for friends.friends14
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends14(String friends14) {
        this.friends14 = friends14 == null ? null : friends14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends15
     *
     * @return the value of friends.friends15
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends15() {
        return friends15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends15
     *
     * @param friends15 the value for friends.friends15
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends15(String friends15) {
        this.friends15 = friends15 == null ? null : friends15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends16
     *
     * @return the value of friends.friends16
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends16() {
        return friends16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends16
     *
     * @param friends16 the value for friends.friends16
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends16(String friends16) {
        this.friends16 = friends16 == null ? null : friends16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends17
     *
     * @return the value of friends.friends17
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends17() {
        return friends17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends17
     *
     * @param friends17 the value for friends.friends17
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends17(String friends17) {
        this.friends17 = friends17 == null ? null : friends17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends18
     *
     * @return the value of friends.friends18
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends18() {
        return friends18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends18
     *
     * @param friends18 the value for friends.friends18
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends18(String friends18) {
        this.friends18 = friends18 == null ? null : friends18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends19
     *
     * @return the value of friends.friends19
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends19() {
        return friends19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends19
     *
     * @param friends19 the value for friends.friends19
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends19(String friends19) {
        this.friends19 = friends19 == null ? null : friends19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friends20
     *
     * @return the value of friends.friends20
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public String getFriends20() {
        return friends20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friends20
     *
     * @param friends20 the value for friends.friends20
     *
     * @mbg.generated Tue Mar 31 15:38:01 CDT 2020
     */
    public void setFriends20(String friends20) {
        this.friends20 = friends20 == null ? null : friends20.trim();
    }
}