package com.Ape.dataObject;

public class DO_Merchants {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.id
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.type
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.address
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.mainBusiness
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    private String mainbusiness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.imgUrl
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.usersId
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    private Integer usersid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.stars
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    private Double stars;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.id
     *
     * @return the value of merchants.id
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.id
     *
     * @param id the value for merchants.id
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.type
     *
     * @return the value of merchants.type
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.type
     *
     * @param type the value for merchants.type
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.address
     *
     * @return the value of merchants.address
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.address
     *
     * @param address the value for merchants.address
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.mainBusiness
     *
     * @return the value of merchants.mainBusiness
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public String getMainbusiness() {
        return mainbusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.mainBusiness
     *
     * @param mainbusiness the value for merchants.mainBusiness
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public void setMainbusiness(String mainbusiness) {
        this.mainbusiness = mainbusiness == null ? null : mainbusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.imgUrl
     *
     * @return the value of merchants.imgUrl
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.imgUrl
     *
     * @param imgurl the value for merchants.imgUrl
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.usersId
     *
     * @return the value of merchants.usersId
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public Integer getUsersid() {
        return usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.usersId
     *
     * @param usersid the value for merchants.usersId
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public void setUsersid(Integer usersid) {
        this.usersid = usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.stars
     *
     * @return the value of merchants.stars
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public Double getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.stars
     *
     * @param stars the value for merchants.stars
     *
     * @mbg.generated Sun Mar 15 16:35:56 CDT 2020
     */
    public void setStars(Double stars) {
        this.stars = stars;
    }
}