package com.Ape.dataObject;

public class DO_Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.usersType
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    private String userstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.likeNum
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    private Integer likenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.usersType
     *
     * @return the value of users.usersType
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public String getUserstype() {
        return userstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.usersType
     *
     * @param userstype the value for users.usersType
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public void setUserstype(String userstype) {
        this.userstype = userstype == null ? null : userstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.likeNum
     *
     * @return the value of users.likeNum
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public Integer getLikenum() {
        return likenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.likeNum
     *
     * @param likenum the value for users.likeNum
     *
     * @mbg.generated Sat Apr 04 08:23:52 CDT 2020
     */
    public void setLikenum(Integer likenum) {
        this.likenum = likenum;
    }
}