package com.Ape.dataObject;

public class DO_UsersPassword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_password.id
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_password.encryptPassword
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    private String encryptpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_password.usersId
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    private Integer usersid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_password.id
     *
     * @return the value of users_password.id
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_password.id
     *
     * @param id the value for users_password.id
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_password.encryptPassword
     *
     * @return the value of users_password.encryptPassword
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    public String getEncryptpassword() {
        return encryptpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_password.encryptPassword
     *
     * @param encryptpassword the value for users_password.encryptPassword
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    public void setEncryptpassword(String encryptpassword) {
        this.encryptpassword = encryptpassword == null ? null : encryptpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_password.usersId
     *
     * @return the value of users_password.usersId
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    public Integer getUsersid() {
        return usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_password.usersId
     *
     * @param usersid the value for users_password.usersId
     *
     * @mbg.generated Fri Mar 06 20:55:18 CST 2020
     */
    public void setUsersid(Integer usersid) {
        this.usersid = usersid;
    }
}